config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  # ADMIN PAGES

  get '/admin', to: 'admin/calendar#index'

  get '/bruiloft', to: redirect('/wedding')
  get '/over-onelife-film', to: redirect('/about')
  get '/ervaringen', to: redirect('/about')
  get '/verjaardag', to: redirect('/')
  get '/relaties/compilatie', to: redirect('/')
  get '/relaties/nicolette_bas_short', to: redirect('/films/nicolette-bas-trouwfilm-short')

  match '(*any)', to: redirect(subdomain: ''), via: :all, constraints: {subdomain: 'www'}

  namespace :admin do
    resources :calendar, only: [:index]
    resources :bookings do
      collection do
        get 'all-bookings'
      end
      member do
        patch 'update_state'
        post 'send_reminder', to: 'bookings#send_reminder'
      end
      resources :comments, only: [:create]
    end
    resources :requests do
      member do
        patch 'approve'
        patch 'update_state'
      end
      resources :comments, only: [:create]
      collection do
        get 'cancelled_requests'
        get 'new_arrivals'
      end
    end
    resources :songs, except: [:show] do
      collection do
        get 'slow'
        get 'medium'
        get 'up'
      end
    end
    resources :films
  end

  get 'bruiloft/:id', to: 'films#show'
  # verborgen -- > TO DO: Verborgen?

  resources :films, only: [] do
    resources :comments, only: [:create]
  end
  resources :requests, only: [:create]

  # CLIENT PAGES

  namespace :client do
    resources :bookings, only: [:show, :update] do
      member do
        get 'film'
      end
      resources :playlines, only: [:create]
      resources :song_choices, only: [:index, :create, :destroy]
    end

    resources :playlines, only: [:destroy, :edit, :update] do
      collection do
        patch 'set_order'
      end
    end
  end

  # ERROR PAGES
  get "/404", to: "errors#not_found"
  get "/422", to: "errors#unacceptable"
  get "/500", to: "errors#internal_error"

  # SEO
  get '/sitemap.xml' => 'sitemaps#index', defaults: { format: 'xml' }
  get "/robots.:format", to: "pages#robots"


  # PUBLIC PAGES

  scope '(:locale)', locale: /nl|en/ do

    root to: 'pages#home'
    resources :films, only: [:show]

    # custom pages
    get 'password', to: 'films#password'
    post 'password', to: 'films#password'
    get 'gallery', to: 'pages#gallery'
    get 'about', to: 'pages#about'
    get 'contact', to: 'requests#new'
    get 'wedding', to: 'pages#wedding'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/booking.rb
class Booking < ApplicationRecord
  include PgSearch
  has_many :comments, as: :commentable
  by_star_field :date_wedding
  after_create :add_suggestive_lines

  default_scope { order(date_wedding: :asc) }

  paginates_per 20

  belongs_to :user, optional: true
  belongs_to :request, optional: true
  has_one :film, dependent: :nullify
  has_many :playlines, dependent: :destroy
  has_many :song_choices, dependent: :destroy
  has_many :songs, through: :song_choices
  pg_search_scope :search_by_text, :against => [:name, :location_wedding, :email_address]

  validates :name, presence: true
  validates :email_address, presence: true
  validates :location_wedding, presence: true
  validates :date_wedding, presence: true

  after_create :booking_services

  scope :active, -> { where("state != 'declined' AND date_wedding >= ? ", Date.today)}
  scope :this_month, -> { where('date_wedding BETWEEN ? AND ?', Date.current.beginning_of_month, (Date.current + 1.months).end_of_month) }
  scope :this_week, -> { where('date_wedding BETWEEN ? AND ?', Date.current.beginning_of_week, (Date.current + 1.months).end_of_week) }
  scope :old, -> { where('date_wedding <=  ? ', Date.today) }

  # REAL TIME DATA : RT

  scope :rt_bookings, -> {active.where("request = 'false'").count}

  def filmed?
    filmed
  end

  def filmed!
    self.filmed = true
  end

  def update_state(new_state)
    self.state = new_state
  end

  def days_till_wedding
    (Date.today - self.date_wedding).to_i
  end

  def checklist
    self.attributes.slice("phone_number", "name", "email_address", "location_wedding", "date_wedding", "groom_number")
  end

  def booking_services
    BookingServices.new(self).approve
  end

  def add_suggestive_lines
    Playline::SUGGESTED_LINES.each do |prereq|
      playline = Playline.new(prereq)
      playline.booking = self
      playline.save
    end
  end
end

app/controllers/admin/bookings_controller.rb
class Admin::BookingsController < Admin::AdminController
  before_action :set_booking, only: [:update, :edit, :destroy, :approve, :show, :update_state]
  skip_before_action :set_counts, only: [:create, :update, :update_state, :destroy, :all_bookings, :send_reminder]

  def index
    if query = params[:search] || params[:search_date]
      @title = 'Zoekresultaten'
      @search = true
      @bookings = params[:search] ? Booking.search_by_text(query) : Booking.by_day(Date.parse(query))
      @bookings = @bookings.order(created_at: :desc).decorate
    else
      @bookings = Booking.active.page(params[:page]).decorate
      @paginated = true
      @title = "Actieve bookingen"
      respond_to do |format|
        format.html
        format.js {render 'insert_bookings', bookings: @bookings, title: @title }
      end
    end
  end

  def new
    @booking = Booking.new
  end

  def show
  end

  def create
    @booking = Booking.new(booking_params)
    if @booking.save
      flash[:notice] = "We will address your request shortly"
      redirect_to admin_booking_path(@booking)
    else
      flash[:alert] = "Please review the errors below"
      render :new
    end
  end

  def edit
  end

  def update
   @booking.update(booking_params)
    if @booking.save
      flash[:notice] = "We will address your request shortly"
      redirect_to admin_booking_path(@booking)
    else
      flash[:alert] = "Please review the errors below"
      render :new
    end
  end

  def destroy
    @booking.decline
    @booking.save
    redirect_to admin_aanvragen_path
  end

  def update_state
    @booking.update_state(params[:new_state])
    @booking.save
    @booking = @booking.decorate
    render 'update_state'
  end

  def all_bookings
    @paginated = true
    @bookings = Booking.page(params[:page]).decorate
    @title = 'Alle boekingen'
    render 'insert_bookings'
  end

  def send_reminder
    BookingMailer.reminder(@booking).deliver_now
  end

private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:phone_number, :date_wedding, :location_wedding, :name, :email_address, :subject, :description)
  end

end

app/controllers/client/bookings_controller.rb
class Client::BookingsController < ApplicationController
  layout 'client'
  before_action :set_booking

  def show
    if @booking.filmed?
      redirect_to film_client_booking_path(@booking)
    end
    @times = Playline::TIMES
    @playline = Playline.new
    unless current_user.booking == @booking || current_user.admin
      redirect_to root_path
      flash[:alert] = "No access"
    end
  end

  def film
    @film = @booking.film
    @film_id = @film.vimeo_id
  end

  before_action :set_booking

  def update
    if @booking.update(booking_params)
      redirect_to client_booking_path(@booking)
      flash[:notice] = "Checklist updated!"
    else
      render 'client/bookings/show'
    end
  end

  private

  def set_booking
    @booking = Booking.find(params[:id]).decorate
    set_counts
  end

  def booking_params
    params.require(:booking).permit(:phone_number, :date_wedding, :location_wedding, :name, :email_address, :subject, :message, :groom_number)
  end

  def set_counts
    p_count = @booking.playlines.count
    @count = p_count > 0 ? p_count : ""
    m_count = @booking.song_choices.count
    @music_count = m_count > 0 ? m_count : ""
  end

end

app/controllers/client/client_controller.rb
class Client::ClientController < ApplicationController
  # layout 'client'
  # before_action :set_booking

  # def set_booking
  #   @booking = Booking.find(params[:id]).decorate
  #   set_counts
  # end

  # def set_counts
  #   p_count = @booking.playlines.count
  #   @count = p_count > 0 ? p_count : ""
  #   m_count = @booking.song_choices.count
  #   @music_count = m_count > 0 ? m_count : ""
  # end

end

app/controllers/client/playlines_controller.rb
class Client::PlaylinesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:set_order, :update]
  skip_before_action :verify_authenticity_token, only: [:create, :update, :set_order]
  before_action :set_booking, only: [:create]
  before_action :set_playline, except: [:create, :set_order]
  before_action :set_times, except: [:set_order, :destroy]

  def create
    @playline = Playline.new(playline_params)
    @playline.booking = @booking
    @times = Playline::TIMES
    @playline.set_order
    if @playline.save
      respond_to do |format|
        format.html { redirect_to client_booking_path(@booking) }
        format.js
      end
    else
      respond_to do |format|
        format.html { render 'client/bookings/show' }
        format.js
      end
    end
  end

  def edit
    @times = Playline::TIMES
    respond_to do |format|
      format.js
    end
  end
  # CAN ONLY EDIT ONE AT THE TIME!

  def update
    @playline.update(playline_params)
    @booking = @playline.booking
    if @playline.save
      respond_to do |format|
        format.html { render 'client/bookings/show' }
        format.json { @playine.to_json }
        format.js
      end
    else
      respond_to do |format|
        format.html { render 'client/bookings/show' }
        format.json { @playine.to_json }
        format.js
      end
    end
  end

  def set_order
    new_order = params[:new_order]
    new_order.each do |key, value|
      playline = Playline.find(key)
      playline.order_number = value
      playline.save
    end
    # @playline.order_number = params[:order_number]
    # @playline.save
  end

  def destroy
    booking = @playline.booking
    @playline.destroy
    respond_to do |format|
      format.html {redirect_to client_booking_path(booking)}
      format.js
    end
  end

  private

  def set_times
    @times = Playline::TIMES
  end

  def set_playline
    @playline = Playline.find(params[:id])
  end


  def set_booking
    @booking = Booking.find(params[:booking_id])
  end

  def set_order_params
    params.require(:new_order).permit(/\d/)
  end

  def playline_params
    params.require(:playline).permit(:begin_time, :end_time, :content, :city, :address, :contact, :phone_number)
  end
end

app/controllers/client/song_choices_controller.rb
class Client::SongChoicesController < ApplicationController
  before_action :set_booking, only: [:create, :destroy, :index]
  before_action :set_song_choice, only: [:destroy]
  layout 'client'

  def index
    @label = params[:type] || "slow"
    @selection = Song.where(label: @label)
    @song_choice = SongChoice.new(booking: @booking)
    @songs = @booking.song_choices
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @song_choice = SongChoice.new(song_choice_params)
    @song_choice.booking = @booking
    if @song_choice.save
      respond_to do |format|
        format.html {redirect_to songs_client_booking_path(@booking)}
        format.js
      end
    else
      respond_to do |format|
        format.html {render 'client/bookings/songs'}
        format.js
      end
    end
  end

  def destroy
    @song_choice.destroy
  end

private

  def song_choice_params
    params.require(:song_choice).permit(:title, :artist, :song_id)
  end

  def set_booking
    @booking = Booking.find(params[:booking_id]).decorate
    set_counts
  end

  def set_song_choice
    @song_choice = SongChoice.find(params[:id])
  end

  def set_counts
    p_count = @booking.playlines.count
    @count = p_count > 0 ? p_count : ""
    m_count = @booking.song_choices.count
    @music_count = m_count > 0 ? m_count : ""
  end
end

app/helpers/admin/bookings_helper.rb
module Admin::BookingsHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/client/bookings/_checklist.html.erb
<div class="modal fade" id="checklist" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title text-center" id="myModalLabel">CHECKLIST</h4>
      </div>
      <div class="modal-body flexed-checklist">
        <div id="checked-data" class="check-toggle">
        <ul style="padding: 40px 90px;" class="text-center">
          <% @booking.checklist.each do |key, value| %>
          <li class="flexed-items">
            <p>
              <strong> <%= key.to_s.gsub("_", " ").upcase %>:</strong>
            </p>
            <p>
              <%= (key == "date_wedding" && value) ? value.strftime('%A, %b %d') : value %>
            </p>
          </li>
          <% end %>
        </ul>
      </div>
      <div id="checklist-form" class="check-toggle hide text-center">
        <%= render 'client/bookings/checklist_form', booking: @booking %>
      </div>
    </div>
    <div class="modal-footer">
      <button class="toggle-check check-toggle" type="submit" name="submit"> Edit </button>
      <button class="toggle-check check-toggle hide" type="submit" name="submit"> Back </button>
      <button type="submit" data-dismiss="modal">Close</button>
    </div>
  </div>
</div>
</div>

<script>
  var buttons = document.querySelectorAll('.toggle-check')
  var toggles = document.querySelectorAll('.check-toggle');
  buttons.forEach(button => {button.addEventListener('click', (e) => {
    toggles.forEach(toggle => toggle.classList.toggle('hide'))
  });
})
</script>

app/views/client/bookings/_checklist_form.html.erb
<%= simple_form_for booking, url: client_booking_path(booking), input_html: {class: "inline-form"} do |f| %>
<%= f.input :phone_number, placeholder: "Bride phone", input_html: { class: "checklist-form-input"}  %>
<%= f.input :groom_number, placeholder: "Groom phone", input_html: { class: "checklist-form-input"}  %>
<%= f.input :name, placeholder: "Name bride & groom", input_html: { class: "checklist-form-input"}  %>
<%= f.input :location_wedding, placeholder: "Location Wedding", input_html: { class: "checklist-form-input"}  %>
<div class="input">
  <label for="contact-date"> Date Wedding</label>
  <input type="text" name="booking[date_wedding]" class="checklist-form-input" placeholder="DATE" required autocomplete="off" id="contact-date" value="<%= @booking.date_wedding %>" data-provide="datepicker" data-date-format="dd-mm-yyyy">
</div>
<input type="hidden" name="user">
<div class="flexed-items">
  <%= f.submit value: t('checklist.update_button') %>
</div>
<% end %>

app/views/client/bookings/_info.html.erb
<div class="modal fade" id="infoModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"><%= t('playbook_data.how_to_use.data_welcome') %></h4>
      </div>
      <div class="modal-body">
        <p>
          <%= t("playbook_data.how_to_use.data_content_#{type}") %>
        </p>
      </div>
      <div class="modal-footer">
        <button type="submit" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/client/bookings/film.html.erb
<!--Content Starts-->
<div class="main-container short-width" style="margin-top: 40px; margin-bottom: 100px;">
  <h4 style="text-align: center;"> <%= @film.name %></h4>
  <!--Wide Wrapper Starts-->
  <div class="wide portfolio-one" data-items-gap="15">

    <!--Items Starts-->
    <div class="item">
      <div class="project">

        <iframe src="https://player.vimeo.com/video/<%= @film_id %>?color=a39254&title=0&byline=0&portrait=0" width="640" height="360" frameborder="0"  webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>

      </div>
    </div>
    <!--Items End-->

  </div>
  <!--Wide Wrapper End-->
  <div class="row" style="margin-top: 40px; margin-bottom: 100px;">
    <div class="col-md-6 col-md-offset-3 col-xs-12">
      <% @film.comments.each do |comment| %>
        <%= render 'comments/show', comment: comment %>
      <% end %>
      <%= render 'comments/form', commentable: @film %>
  </div>
</div>
<!--Content End-->

app/views/client/bookings/show.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

<div id="playbook" class="tab-content">
  <div class="container">
    <div class="row">
      <div class="top-table-data">
        <h5>
          <strong> <%= t('playbook_data.day_format') %></strong>
        </h5>
        <button type="submit" name="submit" data-toggle="modal" data-target="#infoModal">
          <%= t('playbook_data.how_to_use.button') %>
        </button>
      </div>
      <div class="table-responsive">
        <div class="table-head">
          <div class="table-header">
            <%= t('playbook_data.playbook_headers.start_time') %>
          </div>
          <div class="table-header">
            <%= t('playbook_data.playbook_headers.activity') %>
          </div>
          <div class="table-header">
            <%= t('playbook_data.playbook_headers.contact') %>
          </div>
          <div class="table-header">
            <%= t('playbook_data.playbook_headers.phone_number') %>
          </div>
          <div class="table-header">
            <%= t('playbook_data.playbook_headers.address') %>
          </div>
          <div class="table-header">
            <%= t('playbook_data.playbook_headers.city') %>
          </div>
          <div class="table-header">
            <%= t('playbook_data.playbook_headers.changes') %>
          </div>
        </div>
        <div class="table-body" id="playlines">
            <% if @booking.playlines.any? %>
            <% @booking.playlines.sort_by(&:order_number).each do |playline| %>
              <%= render 'client/playlines/show', playline: playline %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="playline-form col-xs-12" style="margin-top: 20px;">
        <%= render 'client/playlines/form', booking: @booking, playline: @playline, url: client_booking_playlines_path(@booking) %>
      </div>
    </div>
  </div>
</div>
</div>


<!-- Modal -->
<%= render 'info', type: 'playbook' %>

app/views/client/bookings/songs.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <div class="song-info">
        <div id="message">
          <h5>
            <strong>
              <%= t('music_data.message', max_songs: @booking.max_songs) %>
            </strong>
          </h5>
        </div>
        <button type="submit" name="submit" data-toggle="modal" data-target="#infoModal">
          <%= t('playbook_data.how_to_use.button') %>
        </button>
      </div>
    </div>
    <div class="col-xs-12 col-md-6 square-box ">
      <h4>
        OneLife Collection
      </h4>
      <div class="scroll-box">
        <ul>
          <% @selection.each do |song| %>
          <li>
            <div class="">

              <iframe src="https://open.spotify.com/embed?uri=<%= song.spotify_uri %>" width="300" height="380" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>

              <div class="song-buttons">
                <style>
                  .no-height: {
                    height: 0px !important;
                  }
                </style>
                <%= simple_form_for([@booking, SongChoice.new], input_html: {class: "no-height"}, remote: true, url: client_booking_song_choices_path(@booking),) do |f| %>
                <%= f.input :title, as: :hidden, input_html: { value: song.title } %>
                <%= f.input :artist, as: :hidden, input_html: { value: song.artist } %>
                <button type="submit" name="submit" class="select-button" style="width: 100.2%; margin-top: -123px;">SELECT</button>
                <% end %>
              </div>
            </div>
          </li>
          <% end %>
        </ul>
      </div>
    </div>

    <div class="col-xs-12 col-md-6 square-box">
      <div class="songs-container padding-top-50">
        <h4>
          Selected
        </h4>
        <ul id="selected-songs">
          <% if @songs.any? %>
          <% @songs.each do |song| %>
          <li id=song-choice-id[<%= song.id %>]>
            <div class="song-row">
              <%= song.title.upcase %>
              -
              <%= song.artist.upcase %>
              <%= link_to  client_booking_song_choice_path(@booking, song), method: :delete, data: {confirm: "Sure?"}, remote: true do %>
              <button class="select-button">REMOVE</button>
              <% end %>
            </div>
          </li>
          <% end %>
          <% else %>
          <p id="no-songs-message">
            No songs chosen yet!
          </p>
        </ul>
        <% end %>
        <div id="errors">

        </div>
      </div>
      <div id="song-form">
        <h4>
          Add your own
        </h4>
        <% unless @songs.count >= @booking.max_songs %>
        <%= simple_form_for([@booking, @song_choice], url: client_booking_song_choices_path(@booking), remote: true) do |f| %>
        <%= f.input :title, label: false, placeholder: 'Title of song', input_html: {class: "spaced-form"} %>
        <%= f.input :artist, label: false, placeholder: '...and the artist!', input_html: {class: "spaced-form"} %>
        <button type="submit" name="submit" id="contact-submit">ADD SONG</button>
        <% end %>
        <% else %>
        <h3>
          <%= @songs.count %> of <%= @booking.max_songs %>
        </h3>
        <% end %>
      </div>
    </div>
  </div>
</div>


<%= render 'info', type: 'music' %>