config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  # ADMIN PAGES

  get '/admin', to: 'admin/calendar#index'

  get '/bruiloft', to: redirect('/wedding')
  get '/over-onelife-film', to: redirect('/about')
  get '/ervaringen', to: redirect('/about')
  get '/verjaardag', to: redirect('/')
  get '/relaties/compilatie', to: redirect('/')
  get '/relaties/nicolette_bas_short', to: redirect('/films/nicolette-bas-trouwfilm-short')

  match '(*any)', to: redirect(subdomain: ''), via: :all, constraints: {subdomain: 'www'}

  namespace :admin do
    resources :calendar, only: [:index]
    resources :bookings do
      collection do
        get 'all-bookings'
      end
      member do
        patch 'update_state'
        post 'send_reminder', to: 'bookings#send_reminder'
      end
      resources :comments, only: [:create]
    end
    resources :requests do
      member do
        patch 'approve'
        patch 'update_state'
      end
      resources :comments, only: [:create]
      collection do
        get 'cancelled_requests'
        get 'new_arrivals'
      end
    end
    resources :songs, except: [:show] do
      collection do
        get 'slow'
        get 'medium'
        get 'up'
      end
    end
    resources :films
  end

  get 'bruiloft/:id', to: 'films#show'
  # verborgen -- > TO DO: Verborgen?

  resources :films, only: [] do
    resources :comments, only: [:create]
  end
  resources :requests, only: [:create]

  # CLIENT PAGES

  namespace :client do
    resources :bookings, only: [:show, :update] do
      member do
        get 'film'
      end
      resources :playlines, only: [:create]
      resources :song_choices, only: [:index, :create, :destroy]
    end

    resources :playlines, only: [:destroy, :edit, :update] do
      collection do
        patch 'set_order'
      end
    end
  end

  # ERROR PAGES
  get "/404", to: "errors#not_found"
  get "/422", to: "errors#unacceptable"
  get "/500", to: "errors#internal_error"

  # SEO
  get '/sitemap.xml' => 'sitemaps#index', defaults: { format: 'xml' }
  get "/robots.:format", to: "pages#robots"


  # PUBLIC PAGES

  scope '(:locale)', locale: /nl|en/ do

    root to: 'pages#home'
    resources :films, only: [:show]

    # custom pages
    get 'password', to: 'films#password'
    post 'password', to: 'films#password'
    get 'gallery', to: 'pages#gallery'
    get 'about', to: 'pages#about'
    get 'contact', to: 'requests#new'
    get 'wedding', to: 'pages#wedding'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div id="flash" class="alert alert-info alert-dismissible" role="alert">
    <button class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div id="flash" class="alert alert-warning alert-dismissible" role="alert">
    <button class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>
<% if notice || alert %>
  <%= content_for(:after_js) do %>
    <script>
      setTimeout(function(){
      $('#flash').slideUp();
    }, 5000);
    </script>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<!--Footer Starts-->
<footer class="page-footer clearfix">
  <!--Copyrights-->
  <p class="copyrights pull-left">© ONELIFE FILM | + 31 6 10 55 15 88 | info@onelifefilm.nl </p>

  <!--Social Links-->
  <div class="social-link-wrapper pull-right">
    <a href="https://www.facebook.com/OnelifeFilm" target="_blank" rel="nofollow"><i class="fab fa-facebook-f"></i></a>
    <a href="https://www.instagram.com/one_life_film/" target="_blank" rel="nofollow"><i class="fab fa-instagram"></i></a>
    <a href="/Algemene-Voorwaarden-OnelifeFilm.pdf"><%=  t('terms_and_conditions') %></a>
    <a href="<%= t('language-link') %>"><img src="<%= image_path t('language') %>" alt="" style="width: 70%"></a>

  </div>

  <!--Fullscreen Button-->
</footer>
<!--Footer End-->

app/views/shared/_navbar-client.html.erb
<header class="page-header clearfix">

  <!--Logo Wrapper-->
  <%= link_to root_path, class: "logo-wrapper" do %>
    <%= image_tag 'one_life_logo.png', class: "logo" %>
  <% end %>

  <!--Mobile Menu Icon-->
  <a href="#" class="mobile-nav-button">
    <i class="icon"></i>
  </a>

  <!--Menu Wrapper Starts-->
  <nav class="manu-wrapper">
    <ul>
      <% unless @booking.filmed? %>
      <li id="home">
        <%= link_to t('playbook') + @booking.counted_playline_state, client_booking_path(@booking), class: @booking.colored_playline_state %>
      </li>
      <li id="gallery">
        <%= link_to t('music')+ @booking.counted_music_state, client_booking_song_choices_path(@booking), class: @booking.colored_music_state %>
      </li>
      <li id="gallery">
        <a type="submit" href="" name="submit" data-toggle="modal" data-target="#checklist">
          CHECKLIST
        </a>
      </li>
      <% else %>
      <li id="film">
        <%= link_to "FILM", film_client_booking_path(@booking), type: "submit" %>
      </li>
      <% end %>
    </ul>
  </nav>
  <!--Menu Wrapper End-->

</header>

<%= render 'client/bookings/checklist' %>

app/views/shared/_navbar.html.erb
<header class="page-header clearfix">

  <!--Logo Wrapper-->
  <a href="<%= root_path %>" class="logo-wrapper">
    <%= image_tag "one_life_logo.png", class: "logo" %>
  </a>

  <!--Mobile Menu Icon-->
  <a href="#" class="mobile-nav-button">
    <i class="icon"></i>
  </a>

  <!--Menu Wrapper Starts-->
  <nav class="manu-wrapper">
    <ul>
      <li id="home">
        <%= link_to t('home'), root_path %>
      </li>
      <li id="wedding">
        <%= link_to t('the_wedding'), wedding_path %>
      </li>
      <li id="gallery">
        <%= link_to t('gallery'), gallery_path %>
      </li>
      <li id="about">
        <%= link_to t('about.about'), about_path %>
      </li>
      <li id="contact">
        <%= link_to t('contact'), contact_path %>
      </li>
    </ul>
  </nav>
  <!--Menu Wrapper End-->
</header>