config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  # ADMIN PAGES

  get '/admin', to: 'admin/calendar#index'

  get '/bruiloft', to: redirect('/wedding')
  get '/over-onelife-film', to: redirect('/about')
  get '/ervaringen', to: redirect('/about')
  get '/verjaardag', to: redirect('/')
  get '/relaties/compilatie', to: redirect('/')
  get '/relaties/nicolette_bas_short', to: redirect('/films/nicolette-bas-trouwfilm-short')

  match '(*any)', to: redirect(subdomain: ''), via: :all, constraints: {subdomain: 'www'}

  namespace :admin do
    resources :calendar, only: [:index]
    resources :bookings do
      collection do
        get 'all-bookings'
      end
      member do
        patch 'update_state'
        post 'send_reminder', to: 'bookings#send_reminder'
      end
      resources :comments, only: [:create]
    end
    resources :requests do
      member do
        patch 'approve'
        patch 'update_state'
      end
      resources :comments, only: [:create]
      collection do
        get 'cancelled_requests'
        get 'new_arrivals'
      end
    end
    resources :songs, except: [:show] do
      collection do
        get 'slow'
        get 'medium'
        get 'up'
      end
    end
    resources :films
  end

  get 'bruiloft/:id', to: 'films#show'
  # verborgen -- > TO DO: Verborgen?

  resources :films, only: [] do
    resources :comments, only: [:create]
  end
  resources :requests, only: [:create]

  # CLIENT PAGES

  namespace :client do
    resources :bookings, only: [:show, :update] do
      member do
        get 'film'
      end
      resources :playlines, only: [:create]
      resources :song_choices, only: [:index, :create, :destroy]
    end

    resources :playlines, only: [:destroy, :edit, :update] do
      collection do
        patch 'set_order'
      end
    end
  end

  # ERROR PAGES
  get "/404", to: "errors#not_found"
  get "/422", to: "errors#unacceptable"
  get "/500", to: "errors#internal_error"

  # SEO
  get '/sitemap.xml' => 'sitemaps#index', defaults: { format: 'xml' }
  get "/robots.:format", to: "pages#robots"


  # PUBLIC PAGES

  scope '(:locale)', locale: /nl|en/ do

    root to: 'pages#home'
    resources :films, only: [:show]

    # custom pages
    get 'password', to: 'films#password'
    post 'password', to: 'films#password'
    get 'gallery', to: 'pages#gallery'
    get 'about', to: 'pages#about'
    get 'contact', to: 'requests#new'
    get 'wedding', to: 'pages#wedding'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/playline.rb
class Playline < ApplicationRecord

  belongs_to :booking
  validates :content, length: { minimum: 2 }

  def set_order
    self.order_number = self.booking.playlines.length + 1
  end

  def numeric_time
    begin_time.gsub(":", ".").to_f if begin_time
  end

  # CONSTANTS

  TIMES = ["5:00", "5:30", "6:00","6:30","7","7:30","8","6:30","9","9:30","10","10:30","11","11:30","12","12:30","13","13:30","14","14:30","15","15:30","16","16:30","17","17:30", "18","18:30","19","19:30","20","20:30","21","21:30","22","22:30","23","23:30","00"]

  SUGGESTED_LINES = [{content: "start time groom", city: "Amsterdam", address: "Keizersgracht 422-2", begin_time: "6:30", phone_number: "06XXXXXXXX", contact: "Mr X", order_number: 1},{content: "start time bride", city: "Amsterdam", address: "Keizersgracht 422-2", begin_time: "6:30", phone_number: "06XXXXXXXX", contact: "Mr X", order_number: 2}, {content: "Putting on wedding dress", city: "Amsterdam", address: "Keizersgracht 422-2", begin_time: "7:30", phone_number: "06XXXXXXXX", contact: "Mr X", order_number: 3}, {content: "Meeting moment bride and groom", city: "Amsterdam", address: "Keizersgracht 422-2", begin_time: "9:00", phone_number: "06XXXXXXXX", contact: "Mr X", order_number: 4}, {content: "Photoshoot", city: "Amsterdam", address: "Keizersgracht 422-2", begin_time: "9:30", phone_number: "06XXXXXXXX", contact: "Mr X", order_number: 5}, {content: "Ceremony", city: "Amsterdam", address: "Keizersgracht 422-2", begin_time: "10:30", phone_number: "06XXXXXXXX", contact: "Mr X", order_number: 6}, {content: "Reception", city: "Amsterdam", address: "Keizersgracht 422-2", begin_time: "14:30", phone_number: "06XXXXXXXX", contact: "Mr X", order_number: 7},{content: "Diner", city: "Amsterdam", address: "Keizersgracht 422-2", begin_time: "17:30", phone_number: "06XXXXXXXX", contact: "Mr X", order_number: 8},{content: "Party", city: "Amsterdam", address: "Keizersgracht 422-2", begin_time: "20:30", phone_number: "06XXXXXXXX", contact: "Mr X", order_number: 9},{content: "Start of film", begin_time: "22:00", order_number: 10}]
end

app/controllers/client/bookings_controller.rb
class Client::BookingsController < ApplicationController
  layout 'client'
  before_action :set_booking

  def show
    if @booking.filmed?
      redirect_to film_client_booking_path(@booking)
    end
    @times = Playline::TIMES
    @playline = Playline.new
    unless current_user.booking == @booking || current_user.admin
      redirect_to root_path
      flash[:alert] = "No access"
    end
  end

  def film
    @film = @booking.film
    @film_id = @film.vimeo_id
  end

  before_action :set_booking

  def update
    if @booking.update(booking_params)
      redirect_to client_booking_path(@booking)
      flash[:notice] = "Checklist updated!"
    else
      render 'client/bookings/show'
    end
  end

  private

  def set_booking
    @booking = Booking.find(params[:id]).decorate
    set_counts
  end

  def booking_params
    params.require(:booking).permit(:phone_number, :date_wedding, :location_wedding, :name, :email_address, :subject, :message, :groom_number)
  end

  def set_counts
    p_count = @booking.playlines.count
    @count = p_count > 0 ? p_count : ""
    m_count = @booking.song_choices.count
    @music_count = m_count > 0 ? m_count : ""
  end

end

app/controllers/client/client_controller.rb
class Client::ClientController < ApplicationController
  # layout 'client'
  # before_action :set_booking

  # def set_booking
  #   @booking = Booking.find(params[:id]).decorate
  #   set_counts
  # end

  # def set_counts
  #   p_count = @booking.playlines.count
  #   @count = p_count > 0 ? p_count : ""
  #   m_count = @booking.song_choices.count
  #   @music_count = m_count > 0 ? m_count : ""
  # end

end

app/controllers/client/playlines_controller.rb
class Client::PlaylinesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:set_order, :update]
  skip_before_action :verify_authenticity_token, only: [:create, :update, :set_order]
  before_action :set_booking, only: [:create]
  before_action :set_playline, except: [:create, :set_order]
  before_action :set_times, except: [:set_order, :destroy]

  def create
    @playline = Playline.new(playline_params)
    @playline.booking = @booking
    @times = Playline::TIMES
    @playline.set_order
    if @playline.save
      respond_to do |format|
        format.html { redirect_to client_booking_path(@booking) }
        format.js
      end
    else
      respond_to do |format|
        format.html { render 'client/bookings/show' }
        format.js
      end
    end
  end

  def edit
    @times = Playline::TIMES
    respond_to do |format|
      format.js
    end
  end
  # CAN ONLY EDIT ONE AT THE TIME!

  def update
    @playline.update(playline_params)
    @booking = @playline.booking
    if @playline.save
      respond_to do |format|
        format.html { render 'client/bookings/show' }
        format.json { @playine.to_json }
        format.js
      end
    else
      respond_to do |format|
        format.html { render 'client/bookings/show' }
        format.json { @playine.to_json }
        format.js
      end
    end
  end

  def set_order
    new_order = params[:new_order]
    new_order.each do |key, value|
      playline = Playline.find(key)
      playline.order_number = value
      playline.save
    end
    # @playline.order_number = params[:order_number]
    # @playline.save
  end

  def destroy
    booking = @playline.booking
    @playline.destroy
    respond_to do |format|
      format.html {redirect_to client_booking_path(booking)}
      format.js
    end
  end

  private

  def set_times
    @times = Playline::TIMES
  end

  def set_playline
    @playline = Playline.find(params[:id])
  end


  def set_booking
    @booking = Booking.find(params[:booking_id])
  end

  def set_order_params
    params.require(:new_order).permit(/\d/)
  end

  def playline_params
    params.require(:playline).permit(:begin_time, :end_time, :content, :city, :address, :contact, :phone_number)
  end
end

app/controllers/client/song_choices_controller.rb
class Client::SongChoicesController < ApplicationController
  before_action :set_booking, only: [:create, :destroy, :index]
  before_action :set_song_choice, only: [:destroy]
  layout 'client'

  def index
    @label = params[:type] || "slow"
    @selection = Song.where(label: @label)
    @song_choice = SongChoice.new(booking: @booking)
    @songs = @booking.song_choices
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @song_choice = SongChoice.new(song_choice_params)
    @song_choice.booking = @booking
    if @song_choice.save
      respond_to do |format|
        format.html {redirect_to songs_client_booking_path(@booking)}
        format.js
      end
    else
      respond_to do |format|
        format.html {render 'client/bookings/songs'}
        format.js
      end
    end
  end

  def destroy
    @song_choice.destroy
  end

private

  def song_choice_params
    params.require(:song_choice).permit(:title, :artist, :song_id)
  end

  def set_booking
    @booking = Booking.find(params[:booking_id]).decorate
    set_counts
  end

  def set_song_choice
    @song_choice = SongChoice.find(params[:id])
  end

  def set_counts
    p_count = @booking.playlines.count
    @count = p_count > 0 ? p_count : ""
    m_count = @booking.song_choices.count
    @music_count = m_count > 0 ? m_count : ""
  end
end

app/controllers/playlines_controller.rb
class PlaylinesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:set_order, :update]
  skip_before_action :verify_authenticity_token, only: [:create, :update, :set_order]
  before_action :set_playbook, only: [:create]
  before_action :set_playline, except: [:create, :set_order]
  before_action :set_times, except: [:set_order, :destroy]

  def create
    @playline = Playline.new(playline_params)
    @playline.playbook = @playbook
    @times = Playline::TIMES
    @playline.set_order
    if @playline.save
      respond_to do |format|
        format.html { redirect_to playbook_path(@playbook) }
        format.js
      end
    else
      respond_to do |format|
        format.html { render 'playbooks/show' }
        format.js
      end
    end
  end

  def edit
    @times = Playline::TIMES
    respond_to do |format|
      format.js
    end
  end
  # CAN ONLY EDIT ONE AT THE TIME!

  def update
    @playline.update(playline_params)
    @playbook = @playline.playbook
    if @playline.save
      respond_to do |format|
        format.html { redirect_to playbook_path(@playbook) }
        format.json { @playine.to_json }
        format.js
      end
    else
      respond_to do |format|
        format.html { render 'playbooks/show' }
        format.json { @playine.to_json }
        format.js
      end
    end
  end

  def set_order
    new_order = params[:new_order]
    new_order.each do |key, value|
      playline = Playline.find(key)
      playline.order_number = value
      playline.save
    end
    # @playline.order_number = params[:order_number]
    # @playline.save
  end

  def destroy
    playbook = @playline.playbook
    @playline.destroy
    respond_to do |format|
      format.html {redirect_to playbook_path(playbook)}
      format.js
    end
  end

  private

  def set_times
    @times = Playline::TIMES
  end

  def set_playline
    @playline = Playline.find(params[:id])
  end


  def set_playbook
    @playbook = Playbook.find(params[:playbook_id])
  end

  def set_order_params
    params.require(:new_order).permit(/\d/)
  end

  def playline_params
    params.require(:playline).permit(:begin_time, :end_time, :content, :city, :address, :contact, :phone_number)
  end
end

app/helpers/playlines_helper.rb
module PlaylinesHelper
end

app/views/client/playlines/_form.html.erb
<%= simple_form_for([booking, playline], url: url, remote: true) do |f| %>
<div class="spaced-around">
  <a href="#" class="time-picker-element-<%= playline.id %> white-square-button" data-time-direction="up" data-time-type="hour">
    <i class="fa fa-sort-asc fa-1x" aria-hidden="true"></i>
  </a>
  <a href="#" class="time-picker-element-<%= playline.id %> white-square-button" data-time-direction="up" data-time-type="minute">
    <i class="fa fa-sort-asc fa-1x" aria-hidden="true"></i>
  </a>
</div>
<div class="inline-form">
  <div class="inline-form-element time-picker">
    <%= f.input :begin_time, label: false, prompt: t('playbook_data.playbook_headers.start_time'), input_html: { class: 'inline-input time-input', id: "time-input-#{playline.id}", value: (playline.begin_time.nil? ? "12:00" : playline.begin_time) }, as: :string, readonly: true %>
  </div>
  <div class="spaced-around" id="block-timepicking">
    <a href="#" class="time-picker-element-<%= playline.id %> white-square-button" data-time-direction="down" data-time-type="hour">
      <i class="fa fa-sort-desc fa-1x" aria-hidden="true"></i>
    </a>
    <a href="#" class="time-picker-element-<%= playline.id %> white-square-button" data-time-direction="down" data-time-type="minute">
      <i class="fa fa-sort-desc fa-1x" aria-hidden="true"></i>
    </a>
  </div>
  <div class="inline-form-element">
    <%= f.input :content, label: false, placeholder: t('playbook_data.playbook_headers.activity'), input_html: { class: 'inline-input' } %>
  </div>
  <div class="inline-form-element">
    <%= f.input :contact, label: false, placeholder: t('playbook_data.playbook_headers.contact'), input_html: { class: 'inline-input' } %>
  </div>
  <div class="inline-form-element">
    <input type="text" name="playline[phone_number]" class="inline-input" placeholder="<%= t('playbook_data.playbook_headers.phone_number') %>" required autocomplete="off" value="<%= playline.phone_number %>">
  </div>
  <div class="inline-form-element">
    <%= f.input :address, label: false, placeholder: t('playbook_data.playbook_headers.address'), input_html: { class: ' inline-input' } %>
  </div>
  <div class="inline-form-element">
    <%= f.input :city, label: false, placeholder: t('playbook_data.playbook_headers.city'), input_html: { class: 'inline-input' } %>
  </div>
  <div class="inline-form-element">
    <%= f.submit value: "ADD LINE" %>
  </div>
</div>
<div class="spaced-around" id="inline-timepicking">
  <a href="#" class="time-picker-element-<%= playline.id %> white-square-button" data-time-direction="down" data-time-type="hour">
    <i class="fa fa-sort-desc fa-1x" aria-hidden="true"></i>
  </a>
  <a href="#" class="time-picker-element-<%= playline.id %> white-square-button" data-time-direction="down" data-time-type="minute">
    <i class="fa fa-sort-desc fa-1x" aria-hidden="true"></i>
  </a>
</div>
<% end %>

app/views/client/playlines/_inline_form.html.erb
<%= simple_form_for([playbook, playline], remote: true) do |f| %>
<td>
  <%= f.input :begin_time, label: false, collection: times, prompt: t('playbook_data.playbook_headers.start_time'), input_html: { class: 'form-content spaced-form' }%>
  </td>
  <td>
  <%= f.input :content, label: false, placeholder: t('playbook_data.playbook_headers.activity'), input_html: { class: 'form-content spaced-form' } %>
  </td>
  <td>
  <%= f.input :contact, label: false, placeholder: t('playbook_data.playbook_headers.contact'), input_html: { class: 'form-contact spaced-form' } %>
</td>
  <td>
    <input type="text" name="playline[phone_number]" placeholder="<%=   t('playbook_data.playbook_headers.phone_number') %>" required autocomplete="off" id="playline_phone_number" class="spaced-form" value="<%= playline.phone_number %>">
  </td>
  <td>
  <%= f.input :address, label: false, placeholder: t('playbook_data.playbook_headers.address'), input_html: { class: 'form-location spaced-form' } %>
  </td>
  <td>
  <%= f.input :city, label: false, placeholder: t('playbook_data.playbook_headers.city'), input_html: { class: 'form-location spaced-form' } %>
  </td>
  <td style="width:100%; height:100%; display:block; text-align:center">
    <button type="submit" style="z-index: 9999; margin-top:4px; height: 45px;" name="submit" id="save-line-button-<%= playline.id %>">SAVE</button>
  </td>
<% end %>

app/views/client/playlines/_show.html.erb
<div class="table-row" draggable="true" id="playline-id[<%= playline.id %>]" data-id="<%= playline.id %>" data-time="<%= playline.numeric_time %>" data-order="<%= playline.order_number %>">
  <div class="table-row-element">
    <%= playline.begin_time %>
  </div>
  <div class="table-row-element">
    <%= playline.content %>
  </div>
  <div class="table-row-element">
    <%= playline.contact %>
  </div>
  <div class="table-row-element">
    <%= playline.phone_number %>
  </div>
  <div class="table-row-element">
    <%= playline.address %>
  </div>
  <div class="table-row-element">
    <%= playline.city %>
  </div>
  <div class="table-row-element">
    <%= link_to  client_playline_path(playline), method: :delete, data: {confirm: "Sure?"}, class: "grey-background-button", remote: true do %>
    <i class="fa fa-trash-o fa-1x" aria-hidden="true"></i>
  <% end %>
  <%= link_to edit_client_playline_path(playline), class: "grey-background-button", remote: true do %>
    <i class="fa fa-pencil fa-1x" aria-hidden="true"></i>
  <% end %>
  </div>
</div>

app/views/client/playlines/create.js.erb
var newLineForm = document.getElementById('new_playline');

<% if @playline.errors.any? %>
  newLineForm.outerHTML = "<%= j render 'client/playlines/form', booking: @booking, playline: @playline, url: client_booking_playline_path(@booking, @playline) %>";
<% else %>
  var lines = document.getElementById('playlines');
  lines.insertAdjacentHTML("beforeend", "<%= j render 'client/playlines/show', playline: @playline %>");
  var line = document.getElementById('playline-id[<%= @playline.id %>]');
  newLineForm.innerHTML = "<%= j render 'client/playlines/form', booking: @booking, playline: Playline.new, url: client_booking_playlines_path(@booking) %>";
<% end %>

sortTable();

app/views/client/playlines/destroy.js.erb
var line = document.getElementById('playline-id[<%= @playline.id %>]');
function remove(element) {
  element.remove();
};
line.classList.toggle('fade');
window.setTimeout(remove(line), 3000);

app/views/client/playlines/edit.js.erb
function changeLineToForm() {
  var line = document.getElementById('playline-id[<%= @playline.id %>]');
  var changeButtons = document.querySelectorAll('.playline-changes');
  line.innerHTML = "<%= j render 'client/playlines/form', booking: @booking, playline: @playline, url: client_playline_path(@playline) %>";
  timePicking("<%= @playline.id %>")
}

changeLineToForm();

app/views/client/playlines/update.js.erb
var line = document.getElementById('playline-id[<%= @playline.id %>]');
<% if @playline.errors.any? %>
  line.innerHTML = "<%= j render 'client/playlines/form', booking: @booking, playline: @playline, url: client_playline_path(@playline) %>";
<% else %>
  line.outerHTML =  "<%= j render 'client/playlines/show', playline: @playline %>";
  sortTable();
<% end %>

app/views/client/playlines/update.json.erb
<% if @playline.errors.any? %>
  { "id": "<%= @playline.id %>",
    "city": "<%= @playline.city %>",
    "address": "<%= @playline.address %>",
    "begin_time": "<%= @playline.begin_time %>",
    "contact": "<%= @playline.contact %>",
    "content": "<%= @playline.content %>",
    "order_number": "<%= @playline.order_number %>",
    "numeric_time": "<%= @playline.numeric_time %>",
    "phone_number": "<%= @playline.phone_number %>",
    "errors": "<%= @playline.errors.to_json %>"
  }
<% else %>
  { "id": "<%= @playline.id %>",
    "city": "<%= @playline.city %>",
    "address": "<%= @playline.address %>",
    "begin_time": "<%= @playline.begin_time %>",
    "contact": "<%= @playline.contact %>",
    "content": "<%= @playline.content %>",
    "order_number": "<%= @playline.order_number %>",
    "numeric_time": "<%= @playline.numeric_time %>",
    "phone_number": "<%= @playline.phone_number %>"
  }
<% end %>